version: '3'
services:
  go-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: back-api
    stdin_open: true
    volumes:
      - ./:/app/back-api
    ports:
     - 8000:8080
    depends_on:
     - db-api
  db-api:
    image: mysql:8.0
    container_name: db-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: pass